name: replace-labels
on: 
  workflow_dispatch: {}
permissions: write-all
jobs:

  call-action:
    runs-on: ubuntu-latest
    steps:
      - uses: scanlonp/github-action-replace-labels@main
        id: replace-labels
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          label-replacement: > 
            { 
              "a": "b", 
              "c": "d" 
            }
          #label-to-replace: abc
          #label-to-replace-with: xyz 