name: replace-labels
on: 
  workflow_dispatch: {}
jobs:
  call-action:
    runs-on: ubuntu-latest
    steps:
      - uses: scanlonp/github-action-replace-labels@main
        id: replace-labels
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          label-to-replace: abc
          label-to-replace-with: xyz 