name: replace-labels
on: 
  workflow_dispatch: {}
jobs:
  call-action:
    runs-on: ubuntu-latest
    steps:
      - uses: scanlonp/github-action-replace-labels@main
        id: github-action-replace-labels